name: Snake Game

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jonathan-ornellas
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#FFFFFF&color_dots=#161B22,#401E5B,#9745F5,#C91E6B,#FF004D

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
